# Generated by Django 5.2.8 on 2025-12-03 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('standalone', 'Standalone Entry'), ('arc', 'Story / Quest Arc'), ('part', 'Part / Chapter / Scene')], default='standalone', max_length=20)),
                ('story_type', models.CharField(choices=[('lore_entry', 'Main Lore Entry'), ('quest', 'Quest'), ('backstory', 'Backstory'), ('world_event', 'World Event'), ('myth', 'Myth / Legend'), ('dialogue', 'Dialogue'), ('other', 'Other')], default='lore_entry', max_length=50)),
                ('visibility', models.CharField(choices=[('draft', 'Draft'), ('private', 'Private'), ('public', 'Public'), ('archived', 'Archived')], default='private', max_length=20)),
                ('in_world_date', models.CharField(blank=True, help_text="e.g. 'Year 1107 AE', 'Before the Archon War'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('characters', models.ManyToManyField(blank=True, related_name='stories', to='core.character')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('factions', models.ManyToManyField(blank=True, related_name='stories', to='core.faction')),
                ('items', models.ManyToManyField(blank=True, related_name='stories', to='core.item')),
                ('locations', models.ManyToManyField(blank=True, related_name='stories', to='core.location')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_stories', to='core.story')),
            ],
            options={
                'ordering': ['kind', 'parent__id', 'order', 'title'],
            },
        ),
    ]
