# Generated by Django 5.2.8 on 2026-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_character_extra_data_alter_character_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='kind',
            field=models.CharField(choices=[('story', 'Story'), ('standalone', 'Standalone'), ('part', 'Part')], default='standalone', max_length=20),
        ),
    ]
