# Generated by Django 5.2.8 on 2026-04-13 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/character/'),
        ),
        migrations.AddField(
            model_name='faction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/faction/'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/item/'),
        ),
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/location/'),
        ),
    ]
