# Generated by Django 5.2.8 on 2026-04-15 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='stories', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='character',
            name='tags',
        ),
        migrations.AlterField(
            model_name='faction',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_factions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='faction',
            name='tags',
        ),
        migrations.AlterField(
            model_name='item',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='item',
            name='tags',
        ),
        migrations.AlterField(
            model_name='location',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='location',
            name='tags',
        ),
        migrations.AlterField(
            model_name='story',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='characters', to='core.tag'),
        ),
        migrations.AddField(
            model_name='faction',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='factions', to='core.tag'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', to='core.tag'),
        ),
        migrations.AddField(
            model_name='location',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='locations', to='core.tag'),
        ),
    ]
