# Generated by Django 5.2.8 on 2026-04-24 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_story_tags_alter_character_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Trait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trait_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traits', to='core.traitset')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='story',
            name='allowed_trait_sets',
            field=models.ManyToManyField(blank=True, related_name='stories', to='core.traitset'),
        ),
        migrations.AddConstraint(
            model_name='traitset',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_trait_set_slug_per_user'),
        ),
        migrations.AddConstraint(
            model_name='trait',
            constraint=models.UniqueConstraint(fields=('trait_set', 'key'), name='unique_trait_key_per_set'),
        ),
    ]
