# Generated by Django 5.2.8 on 2026-04-24 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_traitset_trait_story_allowed_trait_sets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='profile_trait_sets',
            field=models.ManyToManyField(blank=True, related_name='characters', to='core.traitset'),
        ),
        migrations.CreateModel(
            name='CharacterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.character')),
            ],
        ),
    ]
