# Generated by Django 5.2.8 on 2026-04-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_character_profile_trait_sets_characterprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='age',
        ),
        migrations.RemoveField(
            model_name='character',
            name='age_description',
        ),
        migrations.RemoveField(
            model_name='character',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='character',
            name='species',
        ),
    ]
