# Generated by Django 5.2.8 on 2026-04-30 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_character_age_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_hash', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('ai_mode', models.CharField(max_length=20)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.story')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['story', 'owner', 'input_hash'], name='core_storya_story_i_05758e_idx')],
                'constraints': [models.UniqueConstraint(fields=('story', 'owner', 'input_hash'), name='unique_story_analysis_per_input')],
            },
        ),
    ]
