# Generated by Django 5.2.8 on 2026-05-01 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_storyanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_type', models.CharField(choices=[('story_analysis', 'Story Analysis'), ('character_profile', 'Character Profile')], max_length=50)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'endpoint_type', 'content_hash'], name='core_airequ_owner_i_c159aa_idx'), models.Index(fields=['idempotency_key'], name='core_airequ_idempot_072c07_idx'), models.Index(fields=['status', 'created_at'], name='core_airequ_status_117b90_idx')],
            },
        ),
    ]
