# Generated by Django 5.2.8 on 2026-05-03 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_airequestlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_type', models.CharField(choices=[('story_analysis', 'Story Analysis'), ('character_profile', 'Character Profile')], max_length=50)),
                ('ai_mode', models.CharField(max_length=20)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('total_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
                ('request_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='core.airequestlog')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'endpoint_type', 'created_at'], name='core_aiusag_owner_i_1072dc_idx'), models.Index(fields=['ai_mode', 'created_at'], name='core_aiusag_ai_mode_bdee94_idx'), models.Index(fields=['model', 'created_at'], name='core_aiusag_model_385b37_idx')],
            },
        ),
    ]
